# final program will be called "ex1"
ex1: ex3.o printpgm.o
	gcc -g -std=c99 -o ex1 ex3.o printpgm.o
# compile 
ex3.o: ex3.c
	gcc -g -std=c99 -c ex3.c
printpgm.o: printpgm.c
	gcc -g -std=c99 -c printpgm.c
